/*
 * ═══════════════════════════════════════════════════════════════
 * HEARTS 3D MODEL - SAMIYA WEB APP
 * ═══════════════════════════════════════════════════════════════
 * 
 * Auto-generated by gltfjsx and updated for the project
 * Loads the optimized hearts-transformed.glb file (92% smaller!)
 * 
 * ═══════════════════════════════════════════════════════════════
 */

'use client'

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Hearts(props: any) {
  // Load the transformed GLB file from public/models/
  const { nodes, materials } = useGLTF('/models/hearts-transformed.glb')
  
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.Mesh10.geometry} 
        material={materials['Material.001']} 
        rotation={[-1.287, 1.172, 0.663]} 
      />
    </group>
  )
}

// Preload the model for better performance
useGLTF.preload('/models/hearts-transformed.glb')

/*
 * ═══════════════════════════════════════════════════════════════
 * USAGE:
 * ═══════════════════════════════════════════════════════════════
 * 
 * <Hearts 
 *   position={[0, 0, 0]}   // [x, y, z]
 *   scale={1}              // Size multiplier
 *   rotation={[0, 0, 0]}   // [x, y, z] in radians
 * />
 * 
 * ═══════════════════════════════════════════════════════════════
 */
