/*
 * ═══════════════════════════════════════════════════════════════
 * HEARTS 3D MODEL COMPONENT
 * ═══════════════════════════════════════════════════════════════
 * 
 * Auto-generated by gltfjsx and manually adapted
 * Loads the optimized hearts-transformed.glb file
 * 
 * ═══════════════════════════════════════════════════════════════
 */

'use client'

import { useGLTF } from '@react-three/drei'

export default function Hearts(props: any) {
  // Load the transformed (optimized) GLB file
  const { scene } = useGLTF('/models/hearts-transformed.glb')
  
  return (
    <primitive 
      object={scene} 
      {...props}
    />
  )
}

// Preload the model for better performance
useGLTF.preload('/models/hearts-transformed.glb')

/*
 * ═══════════════════════════════════════════════════════════════
 * USAGE:
 * ═══════════════════════════════════════════════════════════════
 * 
 * <Hearts 
 *   position={[0, 0, 0]}
 *   scale={1}
 *   rotation={[0, 0, 0]}
 * />
 * 
 * ═══════════════════════════════════════════════════════════════
 */
